# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{i18nlocales}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jorge R. Queiruga Tri\303\261anes"]
  s.date = %q{2010-02-23}
  s.default_executable = %q{i18nlocales}
  s.description = %q{Command-line Ruby on Rails I18n locales manager}
  s.email = %q{jqueiruga@gmail.com}
  s.executables = ["i18nlocales"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "test/helper.rb",
     "test/test_i18nlocales.rb"
  ]
  s.homepage = %q{http://github.com/jque/i18nlocales}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["bin"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Command-line Ruby on Rails I18n locales manager}
  s.test_files = [
    "test/helper.rb",
     "test/test_i18nlocales.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, [">= 0.9.2"])
      s.add_runtime_dependency(%q<hpricot>, [">= 0.8.1"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0.9.2"])
      s.add_dependency(%q<hpricot>, [">= 0.8.1"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0.9.2"])
    s.add_dependency(%q<hpricot>, [">= 0.8.1"])
  end
end

